<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'id' => 16,
                'created_at' => '2025-04-24 06:50:14',
                'updated_at' => '2025-04-28 05:10:14',
                'user_id' => 2,
                'title' => 'Bag',
                'photo_img' => 'photo_img/16-680a4fa6e771a.jpg',
                'lost_date' => '2025-04-15',
                'category' => 'Bag',
                'markings' => 'green bag',
                'status' => 'Claimed',
                'bin' => '001',
                'issued_by' => 'Alyza',
                'issued_date' => '2025-04-24',
                'received_by' => 'SAN ISIDRO ADMIN',
                'received_date' => '2025-04-28',
                'postedby' => 'Caly',
                'location' => 'TSU Lucinda',
                'claimed_by' => 'Zaira Samantha Non (Sam)',
            ],
            [
                'id' => 17,
                'created_at' => '2025-04-24 07:02:08',
                'updated_at' => '2025-04-24 07:02:08',
                'user_id' => 2,
                'title' => 'Liptint',
                'photo_img' => 'photo_img/17-680a527037cbb.jpg',
                'lost_date' => '2025-04-21',
                'category' => 'Make-up Essentials',
                'markings' => 'Dazzle me',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU San Isidro',
                'claimed_by' => null,
            ],
            [
                'id' => 19,
                'created_at' => '2025-04-24 07:03:26',
                'updated_at' => '2025-04-28 06:07:14',
                'user_id' => 2,
                'title' => 'Curler',
                'photo_img' => 'photo_img/19-680a52be700af.jpg',
                'lost_date' => '2025-04-16',
                'category' => 'Make-up Essentials',
                'markings' => 'Pink Curler',
                'status' => 'Unclaimed',
                'bin' => '010',
                'issued_by' => 'Sam',
                'issued_date' => '2025-04-17',
                'received_by' => 'Claire',
                'received_date' => '2025-04-24',
                'postedby' => 'Caly',
                'location' => 'TSU San Isidro',
                'claimed_by' => 'Zaira Samantha Non (Sam)',
            ],
            [
                'id' => 22,
                'created_at' => '2025-04-24 07:15:55',
                'updated_at' => '2025-04-24 07:15:55',
                'user_id' => 2,
                'title' => 'Curler',
                'photo_img' => 'photo_img/22-680a55ab288b6.jpg',
                'lost_date' => '2025-04-22',
                'category' => 'Make-up Essentials',
                'markings' => 'Curler',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU Main',
                'claimed_by' => null,
            ],
            [
                'id' => 23,
                'created_at' => '2025-04-24 07:16:44',
                'updated_at' => '2025-04-24 07:16:44',
                'user_id' => 2,
                'title' => 'Lipbalm',
                'photo_img' => 'photo_img/23-680a55dc1b6d4.jpg',
                'lost_date' => '2025-04-21',
                'category' => 'Make-up Essentials',
                'markings' => 'pink lipbalm',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU Main',
                'claimed_by' => null,
            ],
            [
                'id' => 24,
                'created_at' => '2025-04-24 07:19:39',
                'updated_at' => '2025-04-24 07:19:40',
                'user_id' => 2,
                'title' => 'Mascara',
                'photo_img' => 'photo_img/24-680a568bce73c.jpg',
                'lost_date' => '2025-04-22',
                'category' => 'Make-up Essentials',
                'markings' => 'Mascara',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU Main',
                'claimed_by' => null,
            ],
            [
                'id' => 25,
                'created_at' => '2025-04-24 07:21:22',
                'updated_at' => '2025-04-24 07:21:22',
                'user_id' => 2,
                'title' => 'Hair Spray',
                'photo_img' => 'photo_img/25-680a56f225239.jpg',
                'lost_date' => '2025-04-23',
                'category' => 'Make-up Essentials',
                'markings' => 'Hairfix',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU Main',
                'claimed_by' => null,
            ],
            [
                'id' => 26,
                'created_at' => '2025-04-24 07:34:02',
                'updated_at' => '2025-04-26 08:07:46',
                'user_id' => 2,
                'title' => 'Bag',
                'photo_img' => 'photo_img/26-680a59eacfbe5.jpg',
                'lost_date' => '2025-04-16',
                'category' => 'Bag',
                'markings' => 'black bag',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU Main',
                'claimed_by' => null,
            ],
            [
                'id' => 28,
                'created_at' => '2025-04-24 08:05:48',
                'updated_at' => '2025-04-26 08:20:53',
                'user_id' => 2,
                'title' => 'Laptop Bag',
                'photo_img' => 'photo_img/28-680a615c6bbdd.jpg',
                'lost_date' => '2025-04-23',
                'category' => 'Bag',
                'markings' => 'black laptop bag',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU San Isidro',
                'claimed_by' => null,
            ],
            [
                'id' => 29,
                'created_at' => '2025-04-24 08:07:46',
                'updated_at' => '2025-04-24 08:07:47',
                'user_id' => 2,
                'title' => 'Shoulder Bag',
                'photo_img' => 'photo_img/29-680a61d2e7969.jpg',
                'lost_date' => '2025-04-21',
                'category' => 'Bag',
                'markings' => 'Los angeles',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU San Isidro',
                'claimed_by' => null,
            ],
            [
                'id' => 31,
                'created_at' => '2025-04-24 08:13:19',
                'updated_at' => '2025-04-26 08:18:49',
                'user_id' => 2,
                'title' => 'Laptop Bag',
                'photo_img' => 'photo_img/31-680a631f250a4.jpg',
                'lost_date' => '2025-04-18',
                'category' => 'Bag',
                'markings' => 'gray laptop bag',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU San Isidro',
                'claimed_by' => null,
            ],
            [
                'id' => 33,
                'created_at' => '2025-04-24 08:17:02',
                'updated_at' => '2025-04-26 08:15:10',
                'user_id' => 2,
                'title' => 'Backpack',
                'photo_img' => 'photo_img/33-680a63fe7db12.jpg',
                'lost_date' => '2025-04-21',
                'category' => 'Bag',
                'markings' => 'anello',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU San Isidro',
                'claimed_by' => null,
            ],
            [
                'id' => 34,
                'created_at' => '2025-04-24 08:19:28',
                'updated_at' => '2025-04-26 08:21:24',
                'user_id' => 2,
                'title' => 'Backpack',
                'photo_img' => 'photo_img/34-680a64906f082.jpg',
                'lost_date' => '2025-04-21',
                'category' => 'Bag',
                'markings' => 'jansport',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU San Isidro',
                'claimed_by' => null,
            ],
            [
                'id' => 35,
                'created_at' => '2025-04-24 08:47:26',
                'updated_at' => '2025-04-24 08:47:27',
                'user_id' => 3,
                'title' => 'Portable Fan',
                'photo_img' => 'photo_img/35-680a6b1ed254c.jpg',
                'lost_date' => '2025-04-22',
                'category' => 'Electronic Devices',
                'markings' => 'white portable fan',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Sam',
                'location' => 'TSU San Isidro',
                'claimed_by' => null,
            ],
            [
                'id' => 36,
                'created_at' => '2025-04-25 02:54:06',
                'updated_at' => '2025-04-25 02:54:11',
                'user_id' => 2,
                'title' => 'WTP',
                'photo_img' => 'photo_img/36-680b69ce62739.jpg',
                'lost_date' => '2025-04-23',
                'category' => 'Bag',
                'markings' => 'white tote bag',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU San Isidro',
                'claimed_by' => null,
            ],
            [
                'id' => 37,
                'created_at' => '2025-04-25 05:28:43',
                'updated_at' => '2025-04-25 05:28:44',
                'user_id' => 2,
                'title' => 'Eye shadow',
                'photo_img' => 'photo_img/37-680b8e0b86fa9.jpg',
                'lost_date' => '2025-04-22',
                'category' => 'Make-up Essentials',
                'markings' => 'Sace Lady',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU Main',
                'claimed_by' => null,
            ],
            [
                'id' => 38,
                'created_at' => '2025-04-25 05:29:23',
                'updated_at' => '2025-04-25 05:29:23',
                'user_id' => 2,
                'title' => 'Eye lashes',
                'photo_img' => 'photo_img/38-680b8e332b76f.jpg',
                'lost_date' => '2025-04-21',
                'category' => 'Make-up Essentials',
                'markings' => 'DDK',
                'status' => 'Unclaimed',
                'bin' => null,
                'issued_by' => null,
                'issued_date' => null,
                'received_by' => null,
                'received_date' => null,
                'postedby' => 'Caly',
                'location' => 'TSU Main',
                'claimed_by' => null,
            ],
            [
                'id' => 39,
                'created_at' => '2025-04-25 05:32:38',
                'updated_at' => '2025-04-25 05:32:38',
                'user_id' => 2,
                'title' => 'Eye liner',
                'photo_img' => 'photo_img/39-680b8ef633491.jpg',
                'lost_date' =>
        ];

        DB::table('items')->insert($items);

        DB::table('users')->insert([
            [
                'id' => 1,
                'profile' => '',
                'usertype' => 'admin',
                'username' => 'admin',
                'email' => 'admin',
                'first_name' => 'admin',
                'last_name' => 'admin',
                'address' => null,
                'phone' => null,
                'email_verified_at' => '2025-04-24 04:51:40',
                'password' => Hash::make('admin'),
                'remember_token' => null,
                'created_at' => '2025-04-24 04:50:56',
                'updated_at' => '2025-04-28 05:53:42'
            ]
        ]);

        DB::table('item_histories')->insert([
            [
                'id' => 1,
                'item_id' => 19,
                'changed_from' => 'Unclaimed',
                'changed_to' => 'To Be Claimed',
                'action' => 'claimed',
                'changed_by' => 'Zaira Samantha Non (Sam)',
                'created_at' => '2025-04-24 09:05:31',
                'updated_at' => '2025-04-24 09:05:31'
            ],
            [
                'id' => 8,
                'item_id' => 19,
                'changed_from' => 'To Be Claimed',
                'changed_to' => 'Unclaimed',
                'action' => 'status update',
                'changed_by' => 'Admin Two (MAIN)',
                'created_at' => '2025-04-28 06:07:14',
                'updated_at' => '2025-04-28 06:07:14'
            ]
        ]);

        DB::table('migrations')->insert([
            [
                'id' => 1,
                'migration' => '0001_01_01_000000_create_users_table',
                'batch' => 1
            ],
            [
                'id' => 2,
                'migration' => '0001_01_01_000001_create_cache_table',
                'batch' => 1
            ],
            [
                'id' => 3,
                'migration' => '0001_01_01_000002_create_jobs_table',
                'batch' => 1
            ],
            [
                'id' => 4,
                'migration' => '2024_09_21_050710_create_items_table',
                'batch' => 1
            ],
            [
                'id' => 5,
                'migration' => '2025_04_24_041724_create_item_histories_table',
                'batch' => 1
            ]
        ]);

        DB::table('sessions')->insert([
            [
                'id' => 'c9F7gib6yY6ZUvSPbptW9K7Sx1v70vekQ6SIydsn',
                'user_id' => null,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0',
                'payload' => 'YTo4OntzOjY6Il90b2tlbiI7czo0MDoib1RXYU9pY204Rnltanc5OEo1a2hXOGxjamFEVWpocUpobnI2NEV5biI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fXM6MTM6ImNvbXBhcmlzb25fMjYiO2E6NDp7czo4OiJ1cGxvYWRlZCI7czo2NjoiaHR0cDovLzEyNy4wLjAuMTo4MDAwL3N0b3JhZ2UvcGhvdG9faW1nLzY4MWIzNGE2NTEwYWItTCAtIEJhZzcuanBnIjtzOjc6Im1hdGNoZWQiO3M6NjA6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9zdG9yYWdlL3Bob3RvX2ltZy8yNi02ODBhNTllYWNmYmU1LmpwZyI7czo2OiJyZXN1bHQiO2E6Nzp7czoyMjoiZmluYWxfc2ltaWxhcml0eV9zY29yZSI7ZDo5MC44MTtzOjEyOiJnb29kX21hdGNoZXMiO2k6Mzk1O3M6MTY6ImtleXBvaW50c19pbWFnZTEiO2k6MzU2MDtzOjE2OiJrZXlwb2ludHNfaW1hZ2UyIjtpOjE0ODU7czoxNDoibGFiX3NpbWlsYXJpdHkiO2Q6NjkuMzc7czoxNToibWF0Y2hfaW1hZ2VfdXJsIjtzOjUyOiJodHRwOi8vMTI3LjAuMC4xOjUwNTAvc3RhdGljL21hdGNoX3VwbG9hZGVkX2l0ZW0uanBnIjtzOjE1OiJzaWZ0X3NpbWlsYXJpdHkiO2k6MTAwO31zOjE1OiJtYXRjaF9pbWFnZV91cmwiO3M6NTI6Imh0dHA6Ly8xMjcuMC4wLjE6NTA1MC9zdGF0aWMvbWF0Y2hfdXBsb2FkZWRfaXRlbS5qcGciO31zOjEzOiJjb21wYXJpc29uXzcxIjthOjQ6e3M6ODoidXBsb2FkZWQiO3M6NjY6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9zdG9yYWdlL3Bob3RvX2ltZy82ODFiMzRhNjUxMGFiLUwgLSBCYWc3LmpwZyI7czo3OiJtYXRjaGVkIjtzOjYwOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvc3RvcmFnZS9waG90b19pbWcvNzEtNjgwZDBkMGU2MDlhOC5qcGciO3M6NjoicmVzdWx0IjthOjc6e3M6MjI6ImZpbmFsX3NpbWlsYXJpdHlfc2NvcmUiO2Q6OTEuNjE7czoxMjoiZ29vZF9tYXRjaGVzIjtpOjIyNTtzOjE2OiJrZXlwb2ludHNfaW1hZ2UxIjtpOjM1NjA7czoxNjoia2V5cG9pbnRzX2ltYWdlMiI7aTo2Mzk7czoxNDoibGFiX3NpbWlsYXJpdHkiO2Q6NzIuMDM7czoxNToibWF0Y2hfaW1hZ2VfdXJsIjtzOjUyOiJodHRwOi8vMTI3LjAuMC4xOjUwNTAvc3RhdGljL21hdGNoX3VwbG9hZGVkX2l0ZW0uanBnIjtzOjE1OiJzaWZ0X3NpbWlsYXJpdHkiO2k6MTAwO31zOjE1OiJtYXRjaF9pbWFnZV91cmwiO3M6NTI6Imh0dHA6Ly8xMjcuMC4wLjE6NTA1MC9zdGF0aWMvbWF0Y2hfdXBsb2FkZWRfaXRlbS5qcGciO31zOjEzOiJjb21wYXJpc29uXzcyIjthOjQ6e3M6ODoidXBsb2FkZWQiO3M6NjY6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9zdG9yYWdlL3Bob3RvX2ltZy82ODFiMzRhNjUxMGFiLUwgLSBCYWc3LmpwZyI7czo3OiJtYXRjaGVkIjtzOjYwOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvc3RvcmFnZS9waG90b19pbWcvNzItNjgwZDBlZjQ1ZWJlNC5qcGciO3M6NjoicmVzdWx0IjthOjc6e3M6MjI6ImZpbmFsX3NpbWlsYXJpdHlfc2NvcmUiO2Q6OTAuOTk7czoxMjoiZ29vZF9tYXRjaGVzIjtpOjM2MDtzOjE2OiJrZXlwb2ludHNfaW1hZ2UxIjtpOjM1NjA7czoxNjoia2V5cG9pbnRzX2ltYWdlMiI7aTo5ODU7czoxNDoibGFiX3NpbWlsYXJpdHkiO2Q6NjkuOTY7czoxNToibWF0Y2hfaW1hZ2VfdXJsIjtzOjUyOiJodHRwOi8vMTI3LjAuMC4xOjUwNTAvc3RhdGljL21hdGNoX3VwbG9hZGVkX2l0ZW0uanBnIjtzOjE1OiJzaWZ0X3NpbWlsYXJpdHkiO2k6MTAwO31zOjE1OiJtYXRjaF9pbWFnZV91cmwiO3M6NTI6Imh0dHA6Ly8xMjcuMC4wLjE6NTA1MC9zdGF0aWMvbWF0Y2hfdXBsb2FkZWRfaXRlbS5qcGciO31zOjEzOiJjb21wYXJpc29uXzc2IjthOjQ6e3M6ODoidXBsb2FkZWQiO3M6NjY6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9zdG9yYWdlL3Bob3RvX2ltZy82ODFiMzRhNjUxMGFiLUwgLSBCYWc3LmpwZyI7czo3OiJtYXRjaGVkIjtzOjYwOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvc3RvcmFnZS9waG90b19pbWcvNzYtNjgwZTUyMjRhNWJmYi5qcGciO3M6NjoicmVzdWx0IjthOjc6e3M6MjI6ImZpbmFsX3NpbWlsYXJpdHlfc2NvcmUiO2Q6ODQuOTtzOjEyOiJnb29kX21hdGNoZXMiO2k6Mjc4O3M6MTY6ImtleXBvaW50c19pbWFnZTEiO2k6MzU2MDtzOjE2OiJrZXlwb2ludHNfaW1hZ2UyIjtpOjEwMDU7czoxNDoibGFiX3NpbWlsYXJpdHkiO2Q6NDkuNjc7czoxNToibWF0Y2hfaW1hZ2VfdXJsIjtzOjUyOiJodHRwOi8vMTI3LjAuMC4xOjUwNTAvc3RhdGljL21hdGNoX3VwbG9hZGVkX2l0ZW0uanBnIjtzOjE1OiJzaWZ0X3NpbWlsYXJpdHkiO2k6MTAwO31zOjE1OiJtYXRjaF9pbWFnZV91cmwiO3M6NTI6Imh0dHA6Ly8xMjcuMC4wLjE6NTA1MC9zdGF0aWMvbWF0Y2hfdXBsb2FkZWRfaXRlbS5qcGciO31zOjEzOiJjb21wYXJpc29uXzI5IjthOjQ6e3M6ODoidXBsb2FkZWQiO3M6NzU6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9zdG9yYWdlL3Bob3RvX2ltZy82ODFiMzUwYzk4ZWRiLUwtU2hvdWxkZXIgQmFnIDFTLmpwZyI7czo3OiJtYXRjaGVkIjtzOjYwOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvc3RvcmFnZS9waG90b19pbWcvMjktNjgwYTYxZDJlNzk2OS5qcGciO3M6NjoicmVzdWx0IjthOjc6e3M6MjI6ImZpbmFsX3NpbWlsYXJpdHlfc2NvcmUiO2Q6OTQuMzI7czoxMjoiZ29vZF9tYXRjaGVzIjtpOjIwNDtzOjE2OiJrZXlwb2ludHNfaW1hZ2UxIjtpOjQ3NjtzOjE2OiJrZXlwb2ludHNfaW1hZ2UyIjtpOjE0MTU7czoxNDoibGFiX3NpbWlsYXJpdHkiO2Q6ODEuMDg7czoxNToibWF0Y2hfaW1hZ2VfdXJsIjtzOjUyOiJodHRwOi8vMTI3LjAuMC4xOjUwNTAvc3RhdGljL21hdGNoX3VwbG9hZGVkX2l0ZW0uanBnIjtzOjE1OiJzaWZ0X3NpbWlsYXJpdHkiO2k6MTAwO31zOjE1OiJtYXRjaF9pbWFnZV91cmwiO3M6NTI6Imh0dHA6Ly8xMjcuMC4wLjE6NTA1MC9zdGF0aWMvbWF0Y2hfdXBsb2FkZWRfaXRlbS5qcGciO319',
                'last_activity' => 1746614813
            ]
        ]);
    }
}
