<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsTableSeeder extends Seeder
{
    public function run(): void
    {
        try {
            if (DB::table('items')->count() > 0) {
                $this->command->info('Items already exist, skipping seeding.');
                return;
            }

            DB::table('items')->insert([
                [
                    'id' => 16,
                    'created_at' => '2025-04-24 06:50:14',
                    'updated_at' => '2025-04-28 05:10:14',
                    'user_id' => 2,
                    'title' => 'Bag',
                    'photo_img' => 'photo_img/16-680a4fa6e771a.jpg',
                    'lost_date' => '2025-04-15',
                    'category' => 'Bag',
                    'markings' => 'green bag',
                    'status' => 'Claimed',
                    'bin' => '001',
                    'issued_by' => 'Alyza',
                    'issued_date' => '2025-04-24',
                    'received_by' => 'SAN ISIDRO ADMIN',
                    'received_date' => '2025-04-28',
                    'postedby' => 'Caly',
                    'location' => 'TSU Lucinda',
                    'claimed_by' => 'Zaira Samantha Non (Sam)',
                ],
                [
                    'id' => 17,
                    'created_at' => '2025-04-24 07:02:08',
                    'updated_at' => '2025-04-24 07:02:08',
                    'user_id' => 2,
                    'title' => 'Liptint',
                    'photo_img' => 'photo_img/17-680a527037cbb.jpg',
                    'lost_date' => '2025-04-21',
                    'category' => 'Make-up Essentials',
                    'markings' => 'Dazzle me',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => null,
                ],
                [
                    'id' => 19,
                    'created_at' => '2025-04-24 07:03:26',
                    'updated_at' => '2025-04-28 06:07:14',
                    'user_id' => 2,
                    'title' => 'Curler',
                    'photo_img' => 'photo_img/19-680a52be700af.jpg',
                    'lost_date' => '2025-04-16',
                    'category' => 'Make-up Essentials',
                    'markings' => 'Pink Curler',
                    'status' => 'Unclaimed',
                    'bin' => '010',
                    'issued_by' => 'Sam',
                    'issued_date' => '2025-04-17',
                    'received_by' => 'Claire',
                    'received_date' => '2025-04-24',
                    'postedby' => 'Caly',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => 'Zaira Samantha Non (Sam)',
                ],
                [
                    'id' => 22,
                    'created_at' => '2025-04-24 07:15:55',
                    'updated_at' => '2025-04-24 07:15:55',
                    'user_id' => 2,
                    'title' => 'Curler',
                    'photo_img' => 'photo_img/22-680a55ab288b6.jpg',
                    'lost_date' => '2025-04-22',
                    'category' => 'Make-up Essentials',
                    'markings' => 'Curler',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU Main',
                    'claimed_by' => null,
                ],
                [
                    'id' => 23,
                    'created_at' => '2025-04-24 07:16:44',
                    'updated_at' => '2025-04-24 07:16:44',
                    'user_id' => 2,
                    'title' => 'Lipbalm',
                    'photo_img' => 'photo_img/23-680a55dc1b6d4.jpg',
                    'lost_date' => '2025-04-21',
                    'category' => 'Make-up Essentials',
                    'markings' => 'pink lipbalm',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU Main',
                    'claimed_by' => null,
                ],
                [
                    'id' => 24,
                    'created_at' => '2025-04-24 07:19:39',
                    'updated_at' => '2025-04-24 07:19:40',
                    'user_id' => 2,
                    'title' => 'Mascara',
                    'photo_img' => 'photo_img/24-680a568bce73c.jpg',
                    'lost_date' => '2025-04-22',
                    'category' => 'Make-up Essentials',
                    'markings' => 'Mascara',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU Main',
                    'claimed_by' => null,
                ],
                [
                    'id' => 25,
                    'created_at' => '2025-04-24 07:21:22',
                    'updated_at' => '2025-04-24 07:21:22',
                    'user_id' => 2,
                    'title' => 'Hair Spray',
                    'photo_img' => 'photo_img/25-680a56f225239.jpg',
                    'lost_date' => '2025-04-23',
                    'category' => 'Make-up Essentials',
                    'markings' => 'Hairfix',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU Main',
                    'claimed_by' => null,
                ],
                [
                    'id' => 26,
                    'created_at' => '2025-04-24 07:34:02',
                    'updated_at' => '2025-04-26 08:07:46',
                    'user_id' => 2,
                    'title' => 'Bag',
                    'photo_img' => 'photo_img/26-680a59eacfbe5.jpg',
                    'lost_date' => '2025-04-16',
                    'category' => 'Bag',
                    'markings' => 'black bag',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU Main',
                    'claimed_by' => null,
                ],
                [
                    'id' => 28,
                    'created_at' => '2025-04-24 08:05:48',
                    'updated_at' => '2025-04-26 08:20:53',
                    'user_id' => 2,
                    'title' => 'Laptop Bag',
                    'photo_img' => 'photo_img/28-680a615c6bbdd.jpg',
                    'lost_date' => '2025-04-23',
                    'category' => 'Bag',
                    'markings' => 'black laptop bag',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => null,
                ],
                [
                    'id' => 29,
                    'created_at' => '2025-04-24 08:07:46',
                    'updated_at' => '2025-04-24 08:07:47',
                    'user_id' => 2,
                    'title' => 'Shoulder Bag',
                    'photo_img' => 'photo_img/29-680a61d2e7969.jpg',
                    'lost_date' => '2025-04-21',
                    'category' => 'Bag',
                    'markings' => 'Los angeles',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => null,
                ],
                [
                    'id' => 31,
                    'created_at' => '2025-04-24 08:13:19',
                    'updated_at' => '2025-04-26 08:18:49',
                    'user_id' => 2,
                    'title' => 'Laptop Bag',
                    'photo_img' => 'photo_img/31-680a631f250a4.jpg',
                    'lost_date' => '2025-04-18',
                    'category' => 'Bag',
                    'markings' => 'gray laptop bag',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => null,
                ],
                [
                    'id' => 33,
                    'created_at' => '2025-04-24 08:17:02',
                    'updated_at' => '2025-04-26 08:15:10',
                    'user_id' => 2,
                    'title' => 'Backpack',
                    'photo_img' => 'photo_img/33-680a63fe7db12.jpg',
                    'lost_date' => '2025-04-21',
                    'category' => 'Bag',
                    'markings' => 'anello',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => null,
                ],
                [
                    'id' => 34,
                    'created_at' => '2025-04-24 08:19:28',
                    'updated_at' => '2025-04-26 08:21:24',
                    'user_id' => 2,
                    'title' => 'Backpack',
                    'photo_img' => 'photo_img/34-680a64906f082.jpg',
                    'lost_date' => '2025-04-21',
                    'category' => 'Bag',
                    'markings' => 'jansport',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => null,
                ],
                [
                    'id' => 35,
                    'created_at' => '2025-04-24 08:47:26',
                    'updated_at' => '2025-04-24 08:47:27',
                    'user_id' => 3,
                    'title' => 'Portable Fan',
                    'photo_img' => 'photo_img/35-680a6b1ed254c.jpg',
                    'lost_date' => '2025-04-22',
                    'category' => 'Electronic Devices',
                    'markings' => 'white portable fan',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Sam',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => null,
                ],
                [
                    'id' => 36,
                    'created_at' => '2025-04-25 02:54:06',
                    'updated_at' => '2025-04-25 02:54:11',
                    'user_id' => 2,
                    'title' => 'WTP',
                    'photo_img' => 'photo_img/36-680b69ce62739.jpg',
                    'lost_date' => '2025-04-23',
                    'category' => 'Bag',
                    'markings' => 'white tote bag',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU San Isidro',
                    'claimed_by' => null,
                ],
                [
                    'id' => 37,
                    'created_at' => '2025-04-25 05:28:43',
                    'updated_at' => '2025-04-25 05:28:44',
                    'user_id' => 2,
                    'title' => 'Eye shadow',
                    'photo_img' => 'photo_img/37-680b8e0b86fa9.jpg',
                    'lost_date' => '2025-04-22',
                    'category' => 'Make-up Essentials',
                    'markings' => 'Sace Lady',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU Main',
                    'claimed_by' => null,
                ],
                [
                    'id' => 38,
                    'created_at' => '2025-04-25 05:29:23',
                    'updated_at' => '2025-04-25 05:29:23',
                    'user_id' => 2,
                    'title' => 'Eye lashes',
                    'photo_img' => 'photo_img/38-680b8e332b76f.jpg',
                    'lost_date' => '2025-04-21',
                    'category' => 'Make-up Essentials',
                    'markings' => 'DDK',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU Main',
                    'claimed_by' => null,
                ],
                [
                    'id' => 39,
                    'created_at' => '2025-04-25 05:32:38',
                    'updated_at' => '2025-04-25 05:32:38',
                    'user_id' => 2,
                    'title' => 'Eye liner',
                    'photo_img' => 'photo_img/39-680b8ef633491.jpg',
                    'lost_date' => '2025-04-24',
                    'category' => 'Make-up Essentials',
                    'markings' => 'Black eye liner',
                    'status' => 'Unclaimed',
                    'bin' => null,
                    'issued_by' => null,
                    'issued_date' => null,
                    'received_by' => null,
                    'received_date' => null,
                    'postedby' => 'Caly',
                    'location' => 'TSU Main',
                    'claimed_by' => null,
                ]
            ]);

            $this->command->info('Items seeded successfully.');
        } catch (\Exception $e) {
            $this->command->error('Error seeding items: ' . $e->getMessage());
        }
    }
}
